"""Provider-neutral lifecycle primitives and deterministic provider fixtures."""

from .fake_chatgpt import (
    DeterministicFakeChatGptAdapter,
    FakeChatGptPlan,
    FakeChatGptScenario,
)
from .models import (
    AgentPrincipalRef,
    ApprovalDecision,
    ApprovalRequestedEvent,
    ApprovalResolvedEvent,
    AuditPersistedEvent,
    CapabilityClaim,
    CapabilityEvidence,
    CapabilitySupport,
    CommittedTurn,
    ConversationHandle,
    ConversationState,
    LifecycleEvent,
    OutputDigestDeltaEvent,
    OutputValidatedEvent,
    ProviderCapabilities,
    ProviderResponseStatus,
    ProviderRun,
    ResponseStartedEvent,
    ResponseTerminalEvent,
    ToolCallRequestedEvent,
    ToolCallResolvedEvent,
    ToolResolutionOutcome,
    commit_text_turn,
)
from .state_machine import (
    EventConflictError,
    EventSequenceGapError,
    InvalidLifecycleTransition,
    ProviderRunState,
    apply_lifecycle_event,
    initial_run_state,
)
from .store import (
    AppendResult,
    EventStoreCorruptError,
    EventStoreError,
    LifecycleEventStore,
    UnsupportedSchemaVersion,
)

__all__ = [
    "AgentPrincipalRef",
    "AppendResult",
    "ApprovalDecision",
    "ApprovalRequestedEvent",
    "ApprovalResolvedEvent",
    "AuditPersistedEvent",
    "CapabilityClaim",
    "CapabilityEvidence",
    "CapabilitySupport",
    "CommittedTurn",
    "ConversationHandle",
    "ConversationState",
    "DeterministicFakeChatGptAdapter",
    "EventConflictError",
    "EventSequenceGapError",
    "EventStoreCorruptError",
    "EventStoreError",
    "FakeChatGptPlan",
    "FakeChatGptScenario",
    "InvalidLifecycleTransition",
    "LifecycleEvent",
    "LifecycleEventStore",
    "OutputDigestDeltaEvent",
    "OutputValidatedEvent",
    "ProviderCapabilities",
    "ProviderResponseStatus",
    "ProviderRun",
    "ProviderRunState",
    "ResponseStartedEvent",
    "ResponseTerminalEvent",
    "ToolCallRequestedEvent",
    "ToolCallResolvedEvent",
    "ToolResolutionOutcome",
    "UnsupportedSchemaVersion",
    "apply_lifecycle_event",
    "commit_text_turn",
    "initial_run_state",
]
